sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=opbeat setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: ZHpHtrIezbKL/hIABzcRP8LGS6DjmLKeTK0GhjfdZOu7iuExdOFVWhP343qs96rq7WiuSI7fS3DxncXR0nZq2X7kqjDMr/nkGq0wOjhVEoPMAHN4mwJYeu/SK8FT+RByZZy04tNGfPVNJzpsvpFlDDRDl6uaAYvF0nJ98X0yiI2dlw71aTnD7wImMWr0DUjirWb5qqo7EIUjGk//0XocUFbFfm10yRZqVd+ERy10rS9iPu4RkKke7wBheJa2JIiuvE+zS85EPGnG3BGlq2BEuTmKeoi0/gvBB/mMRdI/a4N/mVgl9aqOj55KaOqtpRXJIEfJE0HJqVHGeIQ0GVY1qoXB3I/bceJu3bAw3KmnZO95pK4In/uqwETWVBrxOLZfLIQw9wXMXzVGGHsc+GykdrTO8yX8GNSqvCJGQ8RWRVijqTJXVDqUKQzlmVOIFcz+TumGog+1Q2HJoUCoWXvsLJ0gVHs1gbEiXne9Wz93am/tPER2j2B4U7RfG2qaKj7cQpAfnzo3alnQxNmTcjY0X9vV4ekqjl3ekwimnc7opkF6mKiJHq2/FrPlnN3/6G2rLVdBZWIyfkF+0FY5QSu1VbLeDcNXNkxyS6yuRU2IKl5GbRe7Y9mpY332fs4wzzwCY5/eM1BZfbhc8pHOgr+fVm+6UXCnuc+eXUWMKvB5j6E=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
